spring:
  application:
    name: gateway-client
  profiles:
    active: default
  cloud:
    gateway:
      # 配置注册中心服务转发，转发后路径默认去掉服务名字
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8001
eureka:
  instance:
    hostname: gateway-client
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
